name: fleet_watch
description: Flutter app that displays cars on a map in real time, allows users to view car details, and track individual cars' locations
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  awesome_snackbar_content: ^0.1.6
  bloc: ^9.0.0
  connectivity_plus: ^6.1.4
  equatable: ^2.0.7
  fleet_repository:
    path: packages/fleet_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.10.0
  flutter_launcher_icons: "^0.14.3"
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  google_maps_flutter: ^2.12.2
  intl: any
  logger: ^2.5.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 
