name: fleet_repository
description: A Dart package combining remote and local data sources for fleet monitoring.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  fleet_api:
    path: ../fleet_api
  hive_fleet_api:
    path: ../hive_fleet_api
  mock_fleet_api:
    path: ../mock_fleet_api
  
dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^7.0.0
