name: fleet_repository
description: A Dart package combining remote and local data sources for fleet monitoring.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  fleet_api:
    path: ../fleet_api
  hive_fleet_api:
    path: ../hive_fleet_api
  meta: ^1.16.0
  mock_fleet_api:
    path: ../mock_fleet_api
  
dev_dependencies:
  mocktail: ^1.0.4
  test: any
  very_good_analysis: ^8.0.0
